name: Build NPM package
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main
  run:
    needs:
      - init

    uses: milaboratory/github-ci-internal/.github/workflows/node-simple.yaml@v4
    with:
      app-name: Amazon Corretto JAVA PL package
      app-name-slug: 'corretto-jdk'
      notify-telegram: true

      node-version: '20.x'
      is-electron-application: 'false'
      always-auth: 'true'

      build-script-name: 'build'

      test: false
      test-script-name: 'test'

      publish-script-name: 'release'

      aws-publish-enable: true
      gcloud-kms-sign-enable: true
      aws-iam-role-to-assume: 'arn:aws:iam::511903394050:role/milab-euce1-prod-github-oidc-role-pl-registry'

    secrets:
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
